Algoritmo "Conta1Ate10_Para"

// Descrição   : Aqui você descreve o que o programa faz! (função)

Var
   C: Inteiro
   
Inicio
      // Exercicio: 1

      // Para C <- 1 ate 10 passo 2 faça -             Pulando de 2 em 2.
      // Escreval(C)
      // FimPara
      
      // Exercicio: 2
      
      // Para C <- 10 ate 1 passo -1 faça -            Regressivo
      // Escreval(C)
      // FimPara
      
      Para C <- 1 ate 10 faça
      Escreval(C)
      FimPara

Fimalgoritmo